### ISSUE TITLE
Problemas al importar

### ISSUE THREAD

**Issue by joacoseco** [landscapedotcl/ng9-rut#1]
tengo el siguiente problema al querer importar la libreria
/node_modules/ng9-rut/ng9-rut"' has no exported member 'Ng2Rut'.

**Comment by danielsotopino** [comment]
como lo estás implementando ?

**Comment by danielsotopino** [comment]
te funcionó @joacoseco

**Comment by joacoseco** [comment]
> como lo estás implementando ?

hago la instalación e importe tal cual dice la documentación

**Comment by danielsotopino** [comment]
oka, revisa la documentación de nuevo plz, cambié los componentes de ng2* a ng9*

**Comment by joacoseco** [comment]
> oka, revisa la documentación de nuevo plz, cambié los componentes de ng2* a ng9*

volví a hacer la instalación y me sigue arrojando este error
/node_modules/ng9-rut/ng9-rut"' has no exported member 'Ng9Rut'.ts(2305)

EDIT: cree un proyecto nuevo para ver si no es la versión de Angular, pero incluso usando Angular 9 me sale el mismo error
