### ISSUE TITLE
Libreria corrupta

### ISSUE THREAD

**Issue by joacoseco** [landscapedotcl/ng9-rut#2]
Al parecer la librería está corrupta, si es que la puedes revisar por favor

**Comment by danielsotopino** [comment]
que problema te da ?

**Comment by danielsotopino** [comment]
Actualicé la documentación, estaba mal.
Acabo de probar sobre un nuevo proyecto, cada feature funciona ok.

Dejo mi ambiente para que compares.

```Angular CLI: 9.1.1
Node: 10.13.0
OS: darwin x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by joacoseco** [comment]
> Actualicé la documentación, estaba mal.
> Acabo de probar sobre un nuevo proyecto, cada feature funciona ok.
> 
> Dejo mi ambiente para que compares.
> 
> ```
> Node: 10.13.0
> OS: darwin x64
> 
> Angular: 9.1.1
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... router
> Ivy Workspace: Yes
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.901.1
> @angular-devkit/build-angular     0.901.1
> @angular-devkit/build-optimizer   0.901.1
> @angular-devkit/build-webpack     0.901.1
> @angular-devkit/core              9.1.1
> @angular-devkit/schematics        9.1.1
> @ngtools/webpack                  9.1.1
> @schematics/angular               9.1.1
> @schematics/update                0.901.1
> rxjs                              6.5.5
> typescript                        3.8.3
> webpack                           4.42.0
> ```

ahora si funciona bien, gracias
