### ISSUE TITLE
Validación cuando el campo es vacío

### ISSUE THREAD

**Issue by danielvaldebenito** [landscapedotcl/ng9-rut#4]
Hola.
Muchas gracias por la librería, me ayuda bastante. Sin embargo hay algo en lo que podría mejorar: si el campo NO es requerido, no debería arrojar el error de rut inválido cuando el campo está vacío.
Lo otro, podría elegir el desarrollador el formato que desea darle al valor del rut  en un formulario (con o sin puntos, con o sin guiones, etc).

Saludos.

**Comment by danielsotopino** [comment]
Buenas @danielvaldebenito, déjame revisar esos issues, estoy algo ocupado en este periodo.
De igual manera estás invitado a hacer la modificación y podemos agregarla dentro de la librería.

**Comment by rvial66f** [comment]
Hola @danielsotopino realice un pull requests con ese cambio, por si lo puedes revisar. Saludos!

**Comment by danielsotopino** [comment]
Hola @rvial66f, voy a revisarlo hoy !
Muchas gracias.

**Comment by danielsotopino** [comment]
@rvial66f se realizó merge y se publicó versión 0.1.0
Muchas gracias por el aporte !
