### ISSUE TITLE
Soporte para Angular 11

### ISSUE THREAD

**Issue by blogcraft** [landscapedotcl/ng9-rut#5]
Al querer actualizar el proyecto a angular 11 muestra un error.

```
Package "ng9-rut" has an incompatible peer dependency to "@angular/common" (requires "^9.1.0" (extended), would install "11.1.2").
Package "ng9-rut" has an incompatible peer dependency to "@angular/core" (requires "^9.1.0" (extended), would install "11.1.2").
```

**Comment by danielsotopino** [comment]
@blogcraft
Acabo de realizar una prueba instalando sobre un angular 11 nuevo y funciona sin problemas.
Desde que versión estás actualizando ?

**Comment by blogcraft** [comment]
El problema no pasa al instalar sobre un proyecto nuevo. 

Es cuando se tiene un proyecto en una versión anterior de angular (por ejemplo 10) y al querer actualizarlo (por ejemplo _ng update @angular/cli_) no deja por que ng9-rut no está hecha para angular 11.

**Comment by danielsotopino** [comment]
@blogcraft oka!
pude reproducir el problema..
se hizo una modificación #5 y publiqué la versión 0.0.7
me comentas como te va :)
