### ISSUE TITLE
rut-helpers Angular 12

### ISSUE THREAD

**Issue by AlejaRo** [landscapedotcl/ng9-rut#8]
Hola.

Pude instalar ng9-rut en mi nuevo proyecto en Angular 12. Sin embargo, al hacer `ng serve`, la consola muestra lo siguiente:

```
Error: node_modules/ng9-rut/public-api.d.ts:7:15 - error TS7016: Could not find a declaration file for module 'rut-helpers'. 'C:/laragon/www/admin-v2/node_modules/rut-helpers/dist/rut-helpers.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/rut-helpers` if it exists or add a new declaration (.d.ts) file containing `declare module 'rut-helpers';`

7 export * from 'rut-helpers';
```

Instalé `rut-helpers` de https://www.npmjs.com/package/rut-helpers pero aún así no funcionó.

¿Me pueden ayudar?
Gracias.

**Comment by danielsotopino** [comment]
Hola @AlejaRo, tienes un proyecto que puedas compartir con el problema ?
Acabo de instalar el paquete en angular 12 y corre sin problemas.

**Comment by AlejaRo** [comment]
Sí, creé este de la misma forma y sólo le instalé el ng9-rut y el rut-helpers: https://github.com/AlejaRo/admin-v2

Me sigue arrojando lo mismo.
![Captura de pantalla 2021-08-19 182418](https://user-images.githubusercontent.com/8749485/130152178-97059a25-c075-47ac-ad37-d9741ef4d831.png)


¡Gracias!

**Comment by danielsotopino** [comment]
@AlejaRo yap, el error debe ocurrir por la nueva versión de angular que está exigiendo las librerías con declarations..
Este componente es el rut-helpers para realizar las validaciones.
Voy a hacer un fork de ese proyecto y haré una actualización para que esté al día y no quede con ese problema.

**Comment by AlejaRo** [comment]
¡Muchas gracias, @danielsotopino!

**Comment by danielsotopino** [comment]
@AlejaRo se liberó la versión 0.1.1, la clase rut-helpers es ahora parte del proyecto.
Hice una prueba con tu proyecto y ahora funciona.
Por favor me comentas si está OK para dejar el issue como resuelto.

**Comment by AlejaRo** [comment]
Hola.
Sí, acabo de hacer la prueba y funciona bien.

Muchas gracias por todo.
¡Saludos!
